version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
shallow_clone: true
dotnet_csproj:
  patch: true
  file: '**\Plugin.FileSystem.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps:
    nuget restore Plugin.FileSystem_CI.sln
build:
  project: Plugin.FileSystem_CI.sln 
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: bR/0Cw2eRUeBiW/ZtJ2yNui38HoUM7kPDhN3POQFdYaE9kH2b+ZCppX+MG8b0xn3
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master