version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
shallow_clone: true
dotnet_csproj:
  patch: true
  file: '**\Plugin.FileSystem.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: >-
    mkdir .\Plugin.FileSystem\bin\Debug
    nuget restore Plugin.FileSystem_CI.sln
build:
  project: Plugin.FileSystem_CI.sln
  verbosity: minimal
artifacts:
- path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: cO5Ki051HsltxSZrXrRsGuFnI3zS3wMOdE6CFoiQz85RBefWY++iyW2QOTtp2ROa
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master